### ISSUE TITLE
Update in packagist, laravel 6.0 support

### ISSUE THREAD

**Issue by moyvera** [mlezcano1985/laravel-pivot-soft-deletes#8]
Can you help with the last change you made to be visible in packagist ?

 Support for Lavavel 6.0

Thanks a lot !

**Comment by moyvera** [comment]
@mlezcano1985 hello !! can you help on this ?

**Comment by mlezcano1985** [comment]
Hi @moyvera. 
I´m sorry, but this repo is deprecated. Consider using another package.
Thanks

**Comment by moyvera** [comment]
Thank you
